### ISSUE TITLE
Assertion failed: detail::isPresent(Val) && "dyn_cast on a non-existent value"

### ISSUE THREAD

**Issue by ghost** [xmos/ai_tools#893]
Hello Deepak, cc Michael,
 
Hello there! I hope everything is going well for you.
 
I encountered some issues with version 1.2.0 of one model that I'm using. However, all ok by reverting to version 1.1.2.dev276.
 
To help you reproduce the error, I've created a script that shows the issue. I've attached the code; the script includes detailed documentation for you to review. (ps: not urgent as dev276 works)
 
If any questions let me know, Regards,
Alberto
[bug_ai_tools_v1.2.0.zip](https://github.com/xmos/ai_tools/files/15077965/bug_ai_tools_v1.2.0.zip)

**Comment by xalbertoisorna** [comment]
> Hello Deepak, cc Michael,
> 
> Hello there! I hope everything is going well for you.
> 
> I encountered some issues with version 1.2.0 of one model that I'm using. However, all ok by reverting to version 1.1.2.dev276.
> 
> To help you reproduce the error, I've created a script that shows the issue. I've attached the code; the script includes detailed documentation for you to review. (ps: not urgent as dev276 works)
> 
> If any questions let me know, Regards, Alberto [bug_ai_tools_v1.2.0.zip](https://github.com/xmos/ai_tools/files/15077965/bug_ai_tools_v1.2.0.zip)
 
Tested with pip install xmos-ai-tools==1.2.1.dev84  https://pypi.org/project/xmos-ai-tools/1.2.1.dev84/
  - Good News: it works! and the tensor arena size is smaller :)
  - Bad news: it is not able to compute the MACS and OPS but maybe is expected? 

 1.2.1.dev84
Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs
<unknown>:0: remark: Tensor arena size : 176960

1.1.2.dev276
Estimated count of arithmetic ops: 0.138 M  ops, equivalently 0.069 M  MACs
<unknown>:0: remark: Tensor arena size : 179544

Also, this is just out of curiosity: could you give more details on what was the issue?

**Comment by ghost** [comment]
That's a good point. We will disable the print of "Estimated count of arithmetic ops: 0.138 M ops, equivalently 0.069 M MACs". It's being printed out from Tensorflow Lite and doesn't have any meaning for us.


> Also, this is just out of curiosity: could you give more details on what was the issue?

Sure, it was a silly bug. When we added in the changes for supporting TransposeConv2D, forgot to add in the case for DepthwiseConv2D. You can see the fix commit here, https://github.com/xmos/ai_tools/pull/894/files
