### ISSUE TITLE
Model output for face deteciton model is different in versions: 1.2.1.dev123 (nok) vs 1.1.2.dev276 (ok)

### ISSUE THREAD

**Issue by xalbertoisorna** [xmos/ai_tools#901]
Hello, 
I have a face detection and recognition model, seems fine on version 1.1.2.dev276 but detections are wrong for later versions, like 1.2.1.dev123, results tends to go to INT8_MIN, –128

I did a minimal example that reproduces this, attached. 

Instructions are in readme.rst. For windows, a file is provided to run it with a single command. 
A clean python venv is recommended. 

[bug_ai_tools___facedet.zip](https://github.com/user-attachments/files/15759268/bug_ai_tools___facedet.zip)

**Comment by ghost** [comment]
Thank you @xalbertoisorna. Please try with the latest beta tools.
Fixed by https://github.com/xmos/ai_tools/pull/902 and released as https://pypi.org/project/xmos-ai-tools/1.2.1.dev143/

**Comment by xalbertoisorna** [comment]
> Thank you @xalbertoisorna. Please try with the latest beta tools. Fixed by #902 and released as https://pypi.org/project/xmos-ai-tools/1.2.1.dev143/

It does improve indeed. 
Outputs have a 97% match rate. Regarding the rest, about 3% of the output goes to -128 (1.2.1.dev143) instead of 127 (1.1.2.dev276). 
For me is accetable. If is ok for you please proceed to close the issue.
